name : First Workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps: 
            - name: Welcome
              run: echo " Welcome"


            - name: list files
              run : ls

            - name : Read file 
              run : cat README.md
    